// <auto-generated />
using LocalScheduleServiceAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalScheduleServiceAPI.Migrations
{
    [DbContext(typeof(LocalContext))]
    partial class LocalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("LocalScheduleServiceAPI.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("GPS")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxNumPeople")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ramp")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZIPCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Locals");
                });

            modelBuilder.Entity("LocalScheduleServiceAPI.Models.LocalBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartDateTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.ToTable("LocalBooking");
                });

            modelBuilder.Entity("LocalScheduleServiceAPI.Models.LocalBooking", b =>
                {
                    b.HasOne("LocalScheduleServiceAPI.Models.Local", "Locals")
                        .WithMany("LocalBooking")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locals");
                });

            modelBuilder.Entity("LocalScheduleServiceAPI.Models.Local", b =>
                {
                    b.Navigation("LocalBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
